ARG FEATURES=

FROM rust:1.89 AS builder
ARG FEATURES
ARG TARGETARCH
WORKDIR /usr/src/autokuma
COPY . .
RUN --mount=type=cache,target=/cache/$TARGETARCH,id=cache-ghcr.io/bigboot/kuma-${FEATURES} \
    cargo install --features "${FEATURES}" --locked --target-dir /cache/$TARGETARCH --path ./kuma-cli 
 
FROM gcr.io/distroless/cc-debian13:debug
COPY --from=builder /usr/local/cargo/bin/kuma /usr/local/bin/kuma

ENTRYPOINT ["/usr/local/bin/kuma"]
CMD ["--help"]