use crate::app_state::{AppDBTables, AppState};
use crate::error::Result;
use futures_util::future::BoxFuture;
use kuma_client::Client;
use std::sync::LazyLock;

type MigrationFn =
    for<'a> fn(&'a AppDBTables, &'a AppState, &'a Client) -> BoxFuture<'a, Result<()>>;

// Generated by build.rs — discovers vN.rs migration files, declares their modules,
// and registers them in MIGRATIONS / CURRENT_VERSION.
include!(concat!(env!("OUT_DIR"), "/migrations_registry.rs"));
